packages:
  - 'apps/*'
  - 'packages/*'
  - 'test/*'
  - '!recipes/*'

allowBuilds:
  '@swc/core': true
  '@tailwindcss/oxide': true
  esbuild: true
  sharp: true

catalog:
  '@types/react': '19.2.14'
  '@types/react-dom': '19.2.3'
  '@types/mustache': '4.2.6'
  '@types/node': '25.6.0'
  '@types/pretty': '2.0.3'
  '@types/yargs-parser': '21.0.3'
  '@tailwindcss/vite': '4.2.4'
  '@vitejs/plugin-react': '6.0.1'
  'autoprefixer': '10.5.0'
  'chalk-template': '1.1.2'
  'clsx': '2.1.1'
  'globby': '16.2.0'
  'hast': '1.0.0'
  'iconoir-react': '7.11.0'
  'js-beautify': '1.15.1'
  'mustache': '4.2.0'
  'postcss': '8.5.14'
  'react': '19.2.5'
  'react-dom': '19.2.5'
  'shiki': '4.0.2'
  'tailwind-merge': '3.3.1'
  'tailwindcss': '4.2.4'
  'tippy.js': '6.3.7'
  'typescript': '6.0.3'
  'unified': '11.0.5'
  'unist-util-visit': '5.1.0'
  'vite': '8.0.10'
  'yargs-parser': '22.0.0'
  'zustand': '5.0.12'

enablePrePostScripts: true
linkWorkspacePackages: false
minimumReleaseAge: 10080 # 7 days
onlyBuiltDependencies:
  - '@moonrepo/cli'
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
shamefullyHoist: true
sharedWorkspaceLockfile: true
