packages:
  - 'apps/*'
  - 'packages/*'
  - 'test/*'
  - '!recipes/*'

enablePrePostScripts: true
linkWorkspacePackages: false
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@moonrepo/cli'
  - esbuild
shamefullyHoist: true
sharedWorkspaceLockfile: true
