name: Pull Request Title Format

on:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  prTitle:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        uses: clowdhaus/actions/pr-title@main
        with:
          on-fail-message: "Your PR title doesn't match the required format. The title should be in the conventional commit (https://www.conventionalcommits.org/en/v1.0.0-beta.4/) format. e.g.\n\n```\nchore: add pr title workflow\n```. Note that scopes should not contain spaces."
          title-regex: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(([*]|[\w|,|\-|\|]+)\))?(!)?\:\s.*'
          github-token: ${{ secrets.GITHUB_TOKEN }}
