name: Run Tests (React v18)

on:
  workflow_dispatch:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
  push:
    branches:
      - '*'
      - '!main'

jobs:
  validate:
    name: Run Tests (React v18)
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Checkout Main
        run: |
          git fetch origin
          git branch -f main origin/main

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install React v18
        run: |
          cd packages/jsx-email
          pnpm add react@^18 react-dom@18
          cd ../create-jsx-email
          pnpm add react@^18 react-dom@18

      - name: Build Projects
        run: |
          moon jsx-email:build
          moon create-jsx-email:build
          moon run :build --query "project~plugin-*"

      - name: Package Tests
        run: moon run jsx-email:test.ci
